default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: journal_app_db_dev
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'alealopez04' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
test:
  adapter: postgresql
  encoding: unicode
  database: journal_app_db_test
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'alealopez04' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  
production:
  primary: &primary_production
    <<: *default
    <% if ENV["DATABASE_URL"] %>
    url: <%= ENV["DATABASE_URL"] %>
    <% else %>
    database: <%= ENV.fetch("DATABASE_NAME", "journal_app_production") %>
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    <% end %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME", "journal_app_production") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME", "journal_app_production") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME", "journal_app_production") %>_cable
    migrations_paths: db/cable_migrate
